inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 22

Metrics/MethodLength:
  Max: 15

Rails/I18nLocaleTexts:
  Enabled: false
